name: Release and Publish

on:
  push:
    branches:
      - main

jobs:
  check-for-changesets:
    runs-on: ubuntu-latest
    outputs:
      has_changesets: ${{ steps.check.outputs.found }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - id: check
        run: |
          if ls .changeset/*.md > /dev/null 2>&1; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

  release:
    needs: check-for-changesets
    if: needs.check-for-changesets.outputs.has_changesets == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Generate index.ts
        run: bash ./index.sh

      - name: Build project
        run: npm run build

      - name: Bump versions
        run: npm run version

      - name: Commit and push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: version bump"
          git push

      - name: Publish to npm
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
